version: '3.7'

services:
  web:
    build: 
      context: ./
      args:
        UID: ${UID}
        GID: ${GID}
    command: gunicorn cool_gifs.wsgi:application --bind 0.0.0.0:8000
    #    expose:
    #  - 8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file: .env.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
