# Generated by Django 2.1.4 on 2019-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
    ]
