# Generated by Django 2.1.4 on 2019-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_store', '0002_auto_20190420_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
