# Generated by Django 2.1.4 on 2019-06-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(height_field='height', upload_to='images/%Y/%m/%d/', width_field='width')),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
