# Generated by Django 2.2.3 on 2019-07-10 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cool_gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
