# Generated by Django 2.2.3 on 2019-07-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_gifs', '0002_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
